#!/usr/bin/env node
/*
 * SocialCrawl credit guard — PreToolUse(Bash) hook.
 *
 * Purpose: never let a paid SocialCrawl call spend credits without the user
 * seeing the cost first, and never let the ban-listed transcript endpoints run.
 * Enforced backstop under skills/_shared/references/credit-guard.md — a rushed,
 * compacted, or injected run can skip the prose, but it cannot skip this.
 *
 * Per-call cost comes from costs.json (generated by tools/socialcrawl/gen_refs.py
 * from the API's OpenAPI spec — all 380 endpoints, exact). Keys are verb-qualified
 * ("POST web/sessions") because cost varies by verb: GET /web/sessions is free, POST
 * is 5 credits. A path not in the map is treated as >=5 credits (ask), so an
 * unknown/new/obfuscated endpoint can't slip through cheap. No hand-maintained list.
 *
 * FAIL-OPEN by contract: fires on EVERY Bash call. Any error, unexpected shape, or
 * missing input -> pass (allow). It must never block a user's shell over a bug here.
 * Commands that don't touch socialcrawl.dev pass through untouched (fast path).
 *
 * Scans EVERY socialcrawl.dev URL in the command (chained curls), denies if any is
 * banned, and gates on the max single-call cost + the cumulative session spend.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

function pass() { process.exit(0); }                  // no decision -> normal permission flow
function emit(obj) {
  // A PreToolUse decision MUST carry hookEventName, and its reason MUST ride in
  // permissionDecisionReason. Claude Code silently discards a decision missing either
  // and lets the tool call through — which is exactly how this guard sat inert from
  // 2026-07-05 to 2026-08-17 while returning a correct-looking "deny" on stdout.
  const out = obj.hookSpecificOutput;
  if (out && out.permissionDecision) {
    out.hookEventName = "PreToolUse";
    if (obj.systemMessage && !out.permissionDecisionReason) {
      out.permissionDecisionReason = obj.systemMessage;
    }
  }
  try { process.stdout.write(JSON.stringify(obj)); } catch {}
  process.exit(0);
}

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  pass();
}

const cmd =
  input && input.tool_input && typeof input.tool_input.command === "string"
    ? input.tool_input.command
    : "";

// Fast path (case-insensitive): almost no Bash call touches SocialCrawl.
if (!cmd.toLowerCase().includes("socialcrawl.dev")) pass();

try {
  // Authoritative cost map (generated). Loaded only now that SocialCrawl is involved.
  let COSTS = null;
  try {
    COSTS = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), "costs.json"), "utf8"));
  } catch {}
  // Minimal fallback for the abnormal case where costs.json is missing — still gate the big guns.
  const FALLBACK_BIG = [
    ["prism/leads", 50], ["prism/creator-vet", 50], ["prism/brand-mentions", 50],
    ["prism/share-of-voice", 40], ["korea-gap", 40], ["prism/campaign", 35],
    ["prism/audience-questions", 30], ["prism/reputation", 30], ["employer-brand", 30],
    ["demand-signals", 30], ["prism/org-radar", 26], ["prism/earned-media", 25],
    ["search/everywhere", 20], ["content_analysis/", 20], ["prism/audience-overlap", 20],
    ["prism/crisis-radar", 15],
  ];

  // HTTP verb for this command. curl defaults to GET; an explicit -X/--request wins,
  // otherwise a body flag implies POST. Flags are command-global, so in a chained command
  // a POST flag can be attributed to a sibling GET URL — that OVER-states cost (asks more
  // often) and never under-states it, which is the safe direction for a spend guard.
  const VERB = (() => {
    const m = cmd.match(/(?:-X|--request)[=\s]+['"]?([A-Za-z]+)/);
    if (m) return m[1].toUpperCase();
    return /(?:^|\s)(?:-d|--data|--data-raw|--data-binary|--data-urlencode|--json)\b/.test(cmd)
      ? "POST"
      : "GET";
  })();

  // Look up a path in the verb-qualified cost map. Falls back through:
  //   exact "VERB path" -> templated match ("web/jobs/{job_id}") -> max across other verbs.
  // Returns null when the map knows nothing about the path.
  // Metered endpoints: the stored number is a UNIT price (per URL / item / chunk / page), so
  // the real spend scales with the array or limit the caller sends. prism/post-stats with 100
  // Instagram URLs is 500 credits, not 1. Quoting the bare number here would be the single
  // most dangerous thing this hook could say.
  const PER_UNIT = (COSTS && COSTS._perUnit) || {};
  function meteredFor(verb, p) {
    const hit = PER_UNIT[`${verb} ${p}`];
    if (hit) return hit;
    for (const k in PER_UNIT) {
      const sp = k.indexOf(" ");
      if (k.slice(sp + 1) === p) return PER_UNIT[k]; // path matches, verb ambiguous -> warn anyway
    }
    return null;
  }

  function lookup(verb, p) {
    if (p === "_perUnit") return null;
    const exact = COSTS[`${verb} ${p}`];
    if (typeof exact === "number") return exact;
    let other = null;
    const worse = (v) => { other = other === null ? v : Math.max(other, v); };
    for (const k in COSTS) {
      if (k === "_perUnit") continue;
      const sp = k.indexOf(" ");
      const kv = k.slice(0, sp);
      const kp = k.slice(sp + 1);
      if (!kp.includes("{")) {
        if (kp === p) worse(COSTS[k]);
        continue;
      }
      const re = new RegExp(
        "^" + kp.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\\\{[a-z_0-9]+\\\}/gi, "[^/]+") + "$"
      );
      if (!re.test(p)) continue;
      if (kv === verb) return COSTS[k];
      worse(COSTS[k]);
    }
    return other;
  }

  // Classify one (already-lowercased) socialcrawl URL. Returns "BANNED" | number of credits.
  function costOf(url) {
    const clean = url.replace(/%2f/gi, "/"); // decode encoded slashes so bans can't be hidden
    const pm = clean.match(/\/v1\/([a-z0-9_/.-]+)/);
    const p = pm ? pm[1].replace(/\?.*$/, "") : "";
    // Ban: any 'transcript' token in the path, or an include=...transcript param.
    if (/transcript/.test(p) || /[?&]include=[^&"'\s]*transcript/.test(clean)) return "BANNED";
    // credits/* (balance, transactions) are account-meta calls that never touch an upstream
    // platform. They sit outside the published platform catalogue, so they are absent from
    // the generated cost map and would otherwise fall through to the conservative 5cr
    // "unknown endpoint" branch and prompt the user on a free call.
    if (p.startsWith("credits/")) return 0;
    // prism/lookup: the catalog, the vendor's pricing.md and utility/endpoints all store 0,
    // but it bills 1 — measured live and uncached 08.23.26. Overridden here rather than in
    // costs.json because costs.json is gen_refs.py output and a regen restores the vendor's 0.
    if (p.startsWith("prism/lookup")) return 1;
    let c;
    if (COSTS) {
      const hit = lookup(VERB, p);
      c = hit === null ? 5 : hit;   // authoritative, or conservative (ask) when unknown
    } else {
      c = 1;                        // no map (abnormal): default cheap, still gate the big guns
      for (const [k, v] of FALLBACK_BIG) if (p.includes(k)) { c = v; break; }
    }
    if (/[?&]deep_scan=true/.test(clean)) c = Math.max(c, 15); // deep-scan variants bill far higher
    return c;
  }

  // EVERY socialcrawl API URL in the command (chained curls, &&, ;, pipes).
  const urls = [...cmd.matchAll(/socialcrawl\.dev\/v1\/[^"'\s]*/gi)].map((m) => m[0].toLowerCase());
  if (urls.length === 0) {
    // Host present but no readable /v1/ URL — the endpoint may be built from shell
    // variables. If this looks like a web request, fail SAFE (ask). A bare mention passes.
    if (/\b(curl|wget|fetch|Invoke-WebRequest)\b/i.test(cmd)) {
      emit({
        hookSpecificOutput: { permissionDecision: "ask" },
        systemMessage:
          "A SocialCrawl request may be assembled from shell variables — its endpoint and credit " +
          "cost can't be read from the command. Confirm the call and its cost with the user first.",
      });
    }
    pass();
  }

  const costs = urls.map(costOf);

  // Metered endpoints anywhere in the command -> always ask, and never quote the bare number.
  const meteredHits = urls
    .map((u) => {
      const clean = u.replace(/%2f/gi, "/");
      const pm = clean.match(/\/v1\/([a-z0-9_/.-]+)/);
      const p = pm ? pm[1].replace(/\?.*$/, "") : "";
      const m = meteredFor(VERB, p);
      return m ? { p, ...m } : null;
    })
    .filter(Boolean);

  // 1. Any banned endpoint anywhere in the command -> deny the whole thing.
  if (costs.includes("BANNED")) {
    emit({
      hookSpecificOutput: { permissionDecision: "deny" },
      systemMessage:
        "BLOCKED: SocialCrawl transcript endpoints (and include=transcript) are banned — no advantage over free captions. Use the local caption -> Whisper chain instead.",
    });
  }

  const paid = costs.filter((c) => typeof c === "number");
  const sum = paid.reduce((a, b) => a + b, 0);
  const max = paid.reduce((a, b) => Math.max(a, b), 0);

  // 2. Metered/per-unit endpoint -> always ask. The stored figure is a unit price, so the real
  //    spend is that figure x however many rows the caller put in the body. Checked BEFORE the
  //    free/cheap fast paths, because a 1cr-per-row endpoint reads as "cheap" and is not.
  if (meteredHits.length) {
    const h = meteredHits[0];
    emit({
      hookSpecificOutput: { permissionDecision: "ask" },
      systemMessage:
        `SocialCrawl METERED call: /v1/${h.p} bills PER ${h.unit.toUpperCase()}, not per request — ` +
        `${h.note}. The cost is that rate multiplied by the number of ${h.unit}s in your body ` +
        `(worst case ~${h.worst}cr each), so a full batch can run into the hundreds of credits. ` +
        `Count the entries, state the real total to the user, and get explicit approval before sending.`,
    });
  }

  // 3. Everything free -> silent pass.
  if (sum === 0) pass();

  // 4. Cumulative session spend (estimated; conservative — counts on intent).
  const sid = String((input && input.session_id) || "nosession").replace(/[^a-z0-9_-]/gi, "");
  const stateFile = join(tmpdir(), `sc-credit-guard-${sid}.json`);
  let spent = 0;
  try { spent = JSON.parse(readFileSync(stateFile, "utf8")).spent || 0; } catch {}
  const total = spent + sum;
  try { writeFileSync(stateFile, JSON.stringify({ spent: total })); } catch {}

  const CAP = 15; // session soft cap before re-confirming
  const many = urls.length > 1 ? ` (${urls.length} calls, ~${sum}cr this command)` : "";

  // 5. Decide.
  if (max >= 5) {
    emit({
      hookSpecificOutput: { permissionDecision: "ask" },
      systemMessage:
        `SocialCrawl PAID call${many}: up to ~${max} credits in one call. Session spend ~${total}cr so far. ` +
        `Approve to spend. If the user's balance may be low, check credits/balance first and offer a cheaper alternative.`,
    });
  }
  if (Math.floor(total / CAP) > Math.floor(spent / CAP)) {
    // crossed another 15cr boundary — re-confirm so a long loop can't run away
    emit({
      hookSpecificOutput: { permissionDecision: "ask" },
      systemMessage:
        `SocialCrawl session spend is ~${total} credits and climbing${many}. ` +
        `Surface the running total to the user and confirm they want to keep going.`,
    });
  }
  // Cheap and under the cap: inform only. No permissionDecision, so the user's normal
  // Bash permission flow still applies — the hook never auto-approves spend.
  emit({ systemMessage: `SocialCrawl call ~${sum}cr (session ~${total}cr).` });
} catch {
  pass(); // any unexpected error -> allow (never block the shell)
}
