#!/usr/bin/env node
/*
 * SocialCrawl credit guard — PreToolUse(Bash) hook.
 *
 * Purpose: never let a paid SocialCrawl call spend credits without the user
 * seeing the cost first, and never let the ban-listed transcript endpoints run.
 * Enforced backstop under skills/_shared/references/credit-guard.md — a rushed,
 * compacted, or injected run can skip the prose, but it cannot skip this.
 *
 * Per-call cost comes from costs.json (generated by tools/socialcrawl/gen_refs.py
 * from the pricing registry — all 333 endpoints, exact). A path not in the map is
 * treated as >=5 credits (ask), so an unknown/new/obfuscated endpoint can't slip
 * through cheap. No hand-maintained cost list to drift.
 *
 * FAIL-OPEN by contract: fires on EVERY Bash call. Any error, unexpected shape, or
 * missing input -> pass (allow). It must never block a user's shell over a bug here.
 * Commands that don't touch socialcrawl.dev pass through untouched (fast path).
 *
 * Scans EVERY socialcrawl.dev URL in the command (chained curls), denies if any is
 * banned, and gates on the max single-call cost + the cumulative session spend.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

function pass() { process.exit(0); }                  // no decision -> normal permission flow
function emit(obj) { try { process.stdout.write(JSON.stringify(obj)); } catch {} process.exit(0); }

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  pass();
}

const cmd =
  input && input.tool_input && typeof input.tool_input.command === "string"
    ? input.tool_input.command
    : "";

// Fast path (case-insensitive): almost no Bash call touches SocialCrawl.
if (!cmd.toLowerCase().includes("socialcrawl.dev")) pass();

try {
  // Authoritative cost map (generated). Loaded only now that SocialCrawl is involved.
  let COSTS = null;
  try {
    COSTS = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), "costs.json"), "utf8"));
  } catch {}
  // Minimal fallback for the abnormal case where costs.json is missing — still gate the big guns.
  const FALLBACK_BIG = [
    ["prism/leads", 50], ["prism/creator-vet", 50], ["prism/brand-mentions", 50],
    ["prism/share-of-voice", 40], ["korea-gap", 40], ["prism/campaign", 35],
    ["prism/audience-questions", 30], ["prism/reputation", 30], ["employer-brand", 30],
    ["demand-signals", 30], ["prism/org-radar", 26], ["prism/earned-media", 25],
    ["search/everywhere", 20], ["content_analysis/", 20], ["prism/audience-overlap", 20],
    ["prism/crisis-radar", 15],
  ];

  // Classify one (already-lowercased) socialcrawl URL. Returns "BANNED" | number of credits.
  function costOf(url) {
    const clean = url.replace(/%2f/gi, "/"); // decode encoded slashes so bans can't be hidden
    const pm = clean.match(/\/v1\/([a-z0-9_/.-]+)/);
    const p = pm ? pm[1].replace(/\?.*$/, "") : "";
    // Ban: any 'transcript' token in the path, or an include=...transcript param.
    if (/transcript/.test(p) || /[?&]include=[^&"'\s]*transcript/.test(clean)) return "BANNED";
    if (p.startsWith("credits/balance") || p.startsWith("prism/lookup")) return 0;
    let c;
    if (COSTS && Object.prototype.hasOwnProperty.call(COSTS, p)) {
      c = COSTS[p];                 // exact, authoritative
    } else if (COSTS) {
      c = 5;                        // map loaded but endpoint unknown -> conservative (ask)
    } else {
      c = 1;                        // no map (abnormal): default cheap, still gate the big guns
      for (const [k, v] of FALLBACK_BIG) if (p.includes(k)) { c = v; break; }
    }
    if (/[?&]deep_scan=true/.test(clean)) c = Math.max(c, 15); // deep-scan variants bill far higher
    return c;
  }

  // EVERY socialcrawl API URL in the command (chained curls, &&, ;, pipes).
  const urls = [...cmd.matchAll(/socialcrawl\.dev\/v1\/[^"'\s]*/gi)].map((m) => m[0].toLowerCase());
  if (urls.length === 0) {
    // Host present but no readable /v1/ URL — the endpoint may be built from shell
    // variables. If this looks like a web request, fail SAFE (ask). A bare mention passes.
    if (/\b(curl|wget|fetch|Invoke-WebRequest)\b/i.test(cmd)) {
      emit({
        hookSpecificOutput: { permissionDecision: "ask" },
        systemMessage:
          "A SocialCrawl request may be assembled from shell variables — its endpoint and credit " +
          "cost can't be read from the command. Confirm the call and its cost with the user first.",
      });
    }
    pass();
  }

  const costs = urls.map(costOf);

  // 1. Any banned endpoint anywhere in the command -> deny the whole thing.
  if (costs.includes("BANNED")) {
    emit({
      hookSpecificOutput: { permissionDecision: "deny" },
      systemMessage:
        "BLOCKED: SocialCrawl transcript endpoints (and include=transcript) are banned — no advantage over free captions. Use the local caption -> Whisper chain instead.",
    });
  }

  const paid = costs.filter((c) => typeof c === "number");
  const sum = paid.reduce((a, b) => a + b, 0);
  const max = paid.reduce((a, b) => Math.max(a, b), 0);

  // 2. Everything free -> silent pass.
  if (sum === 0) pass();

  // 3. Cumulative session spend (estimated; conservative — counts on intent).
  const sid = String((input && input.session_id) || "nosession").replace(/[^a-z0-9_-]/gi, "");
  const stateFile = join(tmpdir(), `sc-credit-guard-${sid}.json`);
  let spent = 0;
  try { spent = JSON.parse(readFileSync(stateFile, "utf8")).spent || 0; } catch {}
  const total = spent + sum;
  try { writeFileSync(stateFile, JSON.stringify({ spent: total })); } catch {}

  const CAP = 15; // session soft cap before re-confirming
  const many = urls.length > 1 ? ` (${urls.length} calls, ~${sum}cr this command)` : "";

  // 4. Decide.
  if (max >= 5) {
    emit({
      hookSpecificOutput: { permissionDecision: "ask" },
      systemMessage:
        `SocialCrawl PAID call${many}: up to ~${max} credits in one call. Session spend ~${total}cr so far. ` +
        `Approve to spend. If the user's balance may be low, check credits/balance first and offer a cheaper alternative.`,
    });
  }
  if (Math.floor(total / CAP) > Math.floor(spent / CAP)) {
    // crossed another 15cr boundary — re-confirm so a long loop can't run away
    emit({
      hookSpecificOutput: { permissionDecision: "ask" },
      systemMessage:
        `SocialCrawl session spend is ~${total} credits and climbing${many}. ` +
        `Surface the running total to the user and confirm they want to keep going.`,
    });
  }
  // Cheap and under the cap: inform only. No permissionDecision, so the user's normal
  // Bash permission flow still applies — the hook never auto-approves spend.
  emit({ systemMessage: `SocialCrawl call ~${sum}cr (session ~${total}cr).` });
} catch {
  pass(); // any unexpected error -> allow (never block the shell)
}
