#!/usr/bin/env node
/*
 * SocialCrawl credit guard — PreToolUse(Bash) hook, and the PostToolUse(Bash) /
 * PostToolUseFailure(Bash) commit (the same script, branching on hook_event_name).
 *
 * Purpose: a silent session cap. Every paid call's quoted worst case is counted against
 * min(500, 25% of the balance) (R18-1, Joe 10.06.26); under the cap nothing is said, one ask comes at each cap
 * step, and every call that cannot be counted asks every time. Silence is only for a PLAIN
 * command (R14a.2, Joe 09.28.26): plain literal curl calls in the plugin's template grammar,
 * which this guard fully reads. Any other command carrying `socialcrawl.dev` (a loop, a pipe
 * into a program, a wrapper, a variable, a heredoc, a note, grep, echo, a commit message, a
 * docs URL) gets the one NOT A PLAIN CURL ask, and is denied unattended.
 * Enforced backstop under skills/_shared/references/credit-guard.md — a rushed,
 * compacted, or injected run can skip the prose, but it cannot skip this.
 *
 * Per-call cost comes from costs.json (generated by tools/socialcrawl/gen_refs.py
 * from the API's OpenAPI spec — all 645 endpoints, exact). Keys are verb-qualified
 * ("POST web/sessions") because cost varies by verb: GET /web/sessions is free, POST
 * is 5 credits. A path not in the map is treated as >=5 credits (ask), so an
 * unknown/new/obfuscated endpoint can't slip through cheap. No hand-maintained list.
 *
 * Each endpoint entry is {credits, label, metered, range: [lo, hi] | null, ...}, priced from
 * the vendor catalogue's own label (R10). A metered entry quotes the top of its range; a null
 * range has no computable ceiling and always ASKS. A "1 credit" endpoint that bills per page
 * is the single most dangerous thing this hook could quote as "~1cr".
 *
 * costs.json also carries three generated blocks this hook reads:
 *   _conditional  a query param that changes the price outright — deep_scan on
 *                 instagram/comment is 15, on tiktok/comment it is 6, and
 *                 get_ad_details on google/company/ads is 25 against a base of 5.
 *   _gated        the 9 transcript endpoints (path ends /transcript), with the per-unit
 *                 price and the cheaper catalog route.
 *   _unpriced     endpoints the vendor has never published a price for.
 *
 * TRANSCRIPT POLICY CHANGED 08.27.26 (Joe's decision, findings §08.27.26b).
 * The 9 transcript endpoints (path ends /transcript) used to be DENIED outright. They are
 * now GATED AND REDIRECTED: the hook returns `ask`, not `deny`. This is a deliberate loosening of a money
 * guard, made for vendor-adoption reasons, and what keeps it safe is the message — it must
 * ALWAYS carry the per-unit price ("10cr PER post, so 100 posts = 1000cr") and the cheaper
 * route. Never let a code change strip the number out of that message; the number IS the
 * control now that the block is gone.
 *
 * Fires on EVERY Bash call. Commands that don't touch socialcrawl.dev, and missing or unreadable
 * input, pass through untouched (fast path). An error past the fast path passes attended (the
 * CLI's own permission prompt still applies) and denies unattended, where a silent pass could
 * spend with nobody there (R14b); in a Post run, whose command has already run, it passes and
 * logs nothing. The exit code is 0 on every path.
 *
 * Scans EVERY socialcrawl.dev URL in the command (chained curls) and decides at COMMAND
 * level: it costs every call, takes the worst severity across them (not plain > gated >
 * unreadable > unbounded > unpriced > cap step), and quotes the SUM of their ceilings as one
 * figure. A call whose cost cannot be computed is a fail-safe ask, never a cheap default.
 * Only a call that runs is counted (Joe, P1): a silent pass commits its worst case in Pre; an
 * ask parks it under the command's sha256 as pending, and the Post run commits it once the
 * command has run. A declined ask is never counted, so the next paid call asks again, and an
 * unattended deny is never counted and never pending. A run before a command that can't record
 * its commit or its pending quote refuses the call, attended and unattended (J6).
 */
import { appendFileSync, existsSync, mkdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { homedir, tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// The ONE exit (P2): it writes the decision, if any, sets process.exitCode and returns. The
// process is never exited explicitly — after a fetch on Node 24/Windows that aborts with rc 127,
// and Claude Code reads a hook's decision only on exit 0. No argument = no decision.
function done(obj) {
  if (obj) {
    // A PreToolUse decision MUST carry hookEventName, and its reason MUST ride in
    // permissionDecisionReason. Claude Code silently discards a decision missing either
    // and lets the tool call through — which is exactly how this guard sat inert from
    // 2026-07-05 to 2026-08-17 while returning a correct-looking "deny" on stdout.
    const out = obj.hookSpecificOutput;
    if (out && out.permissionDecision) {
      out.hookEventName = "PreToolUse";
      if (obj.systemMessage && !out.permissionDecisionReason) {
        out.permissionDecisionReason = obj.systemMessage;
      }
    }
    try { process.stdout.write(JSON.stringify(obj)); } catch {}
  }
  process.exitCode = 0;
}

// Unattended = CLAUDE_CODE_SESSION_ATTENDED=0 (absent = attended). Read before anything can
// throw, so both catches can see it (R14b, O2).
const UNATTENDED = process.env.CLAUDE_CODE_SESSION_ATTENDED === "0";

// The unattended log (R14b, J2/O5): one JSON line per unattended decision past the fast path,
// except a plain free pass, in <revxl>/credit-guard-unattended.jsonl (SC_REVXL_HOME, else
// ~/.claude/revxl). research-suggest.mjs reports new lines on the next prompt. Never the command
// text, never the key: `paths` are the visible /v1/ paths as the cost lookup reads them, with no
// query string. A failed write changes nothing: not the decision, the exit code or stdout.
function logUnattended(sid, decision, kind, paths, cmdWorst, committed, cap) {
  try {
    const override = process.env.SC_REVXL_HOME;
    const dir = override && String(override).trim() ? String(override) : join(homedir(), ".claude", "revxl");
    mkdirSync(dir, { recursive: true });
    appendFileSync(
      join(dir, "credit-guard-unattended.jsonl"),
      JSON.stringify({ ts: new Date().toISOString(), session_id: sid, decision, kind, paths, cmdWorst, committed, cap }) + "\n"
    );
  } catch {}
}

// Set once the input is parsed: a PostToolUse / PostToolUseFailure run, whose command has run.
let POST = false;

// An error inside the guard, in either catch (R14b, O2): attended it passes and the CLI's own
// permission prompt applies; unattended nobody can answer and a pass could spend, so it denies.
// A Post run has nothing left to decide, so its error says nothing and logs nothing (checker X2).
function failed(sid) {
  if (!UNATTENDED || POST) return done();
  logUnattended(sid, "deny", "error", [], null, null, null);
  return done({
    hookSpecificOutput: { permissionDecision: "deny" },
    systemMessage:
      "Unattended session: nobody can confirm this SocialCrawl call, so it was not run. The credit " +
      "guard hit an error reading this command, so it could not count what it would cost.",
  });
}

// The balance read (R14b, O3/O4): GET /v1/credits/balance, 0 credits, which answers
// {"data":{"balance":<number>}} (skills/_shared/references/credit-guard.md). The URL and the key
// come from ledger.mjs, which builds only /v1/credits/ URLs; the request is the global fetch with a
// 3 s timeout. Only a finite number at data.balance is a read. No key (then nothing is sent), a
// failed import, a timeout, a network error, a non-OK status or any other body: null, a failed try.
async function readBalance() {
  try {
    const { ledgerUrl, resolveKey } = await import("./ledger.mjs");
    const key = resolveKey(process.env, homedir());
    if (!key) return null;
    const res = await fetch(ledgerUrl("/v1/credits/balance"), {
      headers: { "x-api-key": key },
      signal: AbortSignal.timeout(3000),
    });
    if (!res.ok) return null;
    const body = await res.json();
    const b = body && body.data ? body.data.balance : null;
    return typeof b === "number" && Number.isFinite(b) ? b : null;
  } catch {
    return null;
  }
}

async function main() {
let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  return done();
}
POST = !!input && (input.hook_event_name === "PostToolUse" || input.hook_event_name === "PostToolUseFailure");

const rawCmd =
  input && input.tool_input && typeof input.tool_input.command === "string"
    ? input.tool_input.command
    : "";

// Fast path (case-insensitive): almost no Bash call touches SocialCrawl.
if (!rawCmd.toLowerCase().includes("socialcrawl.dev")) return done();

// The session state: {spent, pending: {sha256(command): worst}, balance, balanceFails, lost}.
// `balance` is cached by the balance read below (R14b), `balanceFails` counts its failed tries,
// `lost` marks a session whose committed total was lost (J4), and every write keeps all three.
const num = (v) => (typeof v === "number" && Number.isFinite(v) ? v : null);
const sid = String((input && input.session_id) || "nosession").replace(/[^a-z0-9_-]/gi, "");
const stateFile = join(tmpdir(), `sc-credit-guard-${sid}.json`);
const hash = createHash("sha256").update(rawCmd).digest("hex");
function readState() {
  // Local wrap (F-F8). No file is a fresh session, and an old `{spent}` file still reads. A file
  // that is there but can't be read back as a state (any other read error, empty, not JSON, not an
  // object, or a `spent` that is not a finite number) has lost the committed total, so it reads as
  // `lost` (J4): the cap is off and the balance is not read for the rest of the session.
  let raw;
  try {
    raw = readFileSync(stateFile, "utf8");
  } catch (e) {
    return e && e.code === "ENOENT" ? { spent: 0, pending: {} } : { spent: 0, pending: {}, lost: true };
  }
  try {
    const o = JSON.parse(raw);
    if (o && typeof o === "object" && !Array.isArray(o) && (o.spent === undefined || num(o.spent) !== null)) {
      if (!o.pending || typeof o.pending !== "object" || Array.isArray(o.pending)) o.pending = {};
      if (!(num(o.spent) > 0)) o.spent = 0;
      return o;
    }
  } catch {}
  return { spent: 0, pending: {}, lost: true };
}
function writeState(st) {
  // NEVER a non-number: `JSON.stringify({spent: NaN})` is `{"spent":null}`, which would erase every
  // credit already recorded (defect D1). Returns whether the state was saved: a save that does not
  // throw counts as recorded (J6; R18-3, Joe 10.06.26: there is no read-back). A balance read, a
  // silent pass and an ask's pending quote each need that. writeFileSync empties the file before it
  // writes, so a save that fails part-way (a full disk) can leave it empty or cut off: the next read
  // is a lost total. A save that is lost without an error is not detected (a stated LIMIT). A run
  // before a command saves only while it holds the lock below (checker X7). Every `false` has its
  // reason in `why`; a missing folder also ends this run's wait at once (R18-2).
  if (num(st.spent) === null || (!locked && !POST)) return false;
  try {
    writeFileSync(stateFile, JSON.stringify(st));
    return true;
  } catch (e) {
    why = `the session file could not be saved (${(e && e.code) || "error"})`;
    if (e && e.code === "ENOENT") noFolder();
  }
  return false;
}

// One guard run of a session at a time (checker X7): two runs that read the same state and each
// save it back lose one run's count, the last save wins. So a run holds `<state file>.lock`, made
// exclusively, from its read to its last save, and has one 4 s wait to get it. Whatever the create
// fails with (EEXIST while another run holds the lock; EPERM, EBUSY or EACCES as another run
// deletes it), it is tried again every 20 ms, and only the wait running out gives up (checker X8).
// ENOENT is the one exception: with no TEMP folder no wait can help, so the run gives up at once and
// its wait ends there, Pre and Post (R18-2, Joe 10.06.26). A lock older than the hook's 10 s timeout was left by a killed run and
// is cleared. Without the lock a run before a command saves nothing, so a call it has to record is
// refused (J6); a run after a command saves its count anyway, as the command has run. unlock()
// tries a failed delete again, 10 times at most, so a run that ends normally leaves no lock behind.
// ponytail: two runs clearing one stale lock at the same instant can both hold it; a lock with an
// owner check would close that if it is ever seen.
const lockFile = `${stateFile}.lock`;
const nap = () => new Promise((r) => setTimeout(r, 20));
let locked = false;
let until = 0;                                   // when this run's one wait ends
let why = "the session total is not a number";   // why the last save did not happen (J6)
// No session folder (ENOENT): say which folder, and end this run's one wait now (R18-2).
function noFolder() {
  why = `the session folder ${dirname(stateFile)} does not exist (ENOENT), so the session file can't be saved`;
  until = 0;
}
async function lock() {
  until = Date.now() + 4000;
  for (;;) {
    let code;
    try {
      writeFileSync(lockFile, "", { flag: "wx" });
      return (locked = true);
    } catch (e) {
      code = (e && e.code) || "error";
    }
    if (code === "ENOENT") { noFolder(); return false; }
    try {
      if (Date.now() - statSync(lockFile).mtimeMs > 10000) unlinkSync(lockFile);
    } catch {}
    if (Date.now() > until) {
      why =
        `the session lock ${lockFile} could not be taken in 4 seconds (${code}); a lock left by ` +
        `a killed run is cleared once it is 10 seconds old`;
      return false;
    }
    await nap();
  }
}
async function unlock() {
  for (let i = 0; locked && i < 10; i++) {
    try { unlinkSync(lockFile); break; } catch (e) { if (e && e.code === "ENOENT") break; await nap(); }
  }
  locked = false;
}

// PostToolUse(Bash) / PostToolUseFailure(Bash): the command has run (a failed command may still
// have billed — counting it is the safe direction). Commit its pending quote, if it has one. A
// state it can't read back is a lost total here too, and is saved as lost (J4, checker X6). A call
// that has run can't be refused, so a save that fails is tried again until this run's wait ends (at
// once when the session folder is missing, R18-2); if it still can't be saved, the call goes
// uncounted (J6, a stated LIMIT).
if (POST) {
  try {
    await lock();
    const st = readState();
    const w = num(st.pending[hash]);
    if (w !== null) {
      st.spent += w;
      delete st.pending[hash];
    }
    if (w !== null || st.lost) while (!writeState(st) && Date.now() < until) await nap();
  } catch {} finally {
    await unlock();
  }
  return done();
}

try {
  // Heredoc bodies are never masked (Joe 09.28.26, supersedes P4): every SocialCrawl URL anywhere
  // in the command counts, a heredoc body's included. Each mask tried let a body that runs pass
  // at 0 (checker X1, X4). A note written with a URL in it over-counts: a stated LIMIT.
  const cmd = rawCmd;

  // Every ask goes through decide(). Unattended (CLAUDE_CODE_SESSION_ATTENDED=0; absent =
  // attended) nobody can answer, so the ask becomes a deny: never committed, never pending
  // (Joe, P1), and logged under `kind`, the branch that asked (R14b). Attended, the command's
  // worst case waits in `pending` under its sha256 and is committed only by the Post run, so a
  // declined ask is never counted. That pending quote goes through recorded(), so no ask goes out
  // for a call whose quote was not saved. `ask` is the attended-only tail (what to show the user, the
  // yes it needs): unattended it is dropped and the deny ends with its own tail instead (Q-j).
  let st = null;                                 // the session state, read once a call is paid
  function decide(message, worst, kind, ask) {
    if (UNATTENDED) {
      logUnattended(sid, "deny", kind, logPaths(), cmdWorst, st ? st.spent : null, cap);
      return done({
        hookSpecificOutput: { permissionDecision: "deny" },
        systemMessage: `Unattended session: nobody can confirm this SocialCrawl call, so it was not run. ${message}` +
          ` Nothing was counted. If it is needed, run it in an attended session, where it can be confirmed.`,
      });
    }
    if (worst > 0) {
      st.pending[hash] = worst;
      if (!recorded()) return;
    }
    return done({ hookSpecificOutput: { permissionDecision: "ask" }, systemMessage: message + ask });
  }

  // Can't record = refuse (J6). The ONE place a run before a command records what it decided: a
  // silent pass's commit, or an ask's pending quote (a worst case above 0). The record stands once
  // writeState() has saved it without an error (R18-3). When it can't (no session lock within the
  // wait, no session folder, a save that fails), the call is denied, attended and
  // unattended: an ask or a pass here would let a call run that nothing then counts. The message
  // names the reason and the session file, and says to run it again; unattended, the deny is
  // logged as kind `error` with the total as it stood.
  function recorded() {
    if (writeState(st)) return true;
    if (UNATTENDED) logUnattended(sid, "deny", "error", logPaths(), cmdWorst, spent, cap);
    done({
      hookSpecificOutput: { permissionDecision: "deny" },
      systemMessage:
        `SocialCrawl call not run: the credit guard couldn't record it, and a call it can't record ` +
        `would run uncounted (this command's worst case is ~${cmdWorst} credits). Reason: ${why}. ` +
        `Session file: ${stateFile}. Nothing was sent. Run the command again; if it is refused ` +
        `again, check that the session file and its folder exist and can be written.`,
    });
    return false;
  }

  // Authoritative cost map (generated). Loaded only now that SocialCrawl is involved.
  let COSTS = null;
  try {
    COSTS = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), "costs.json"), "utf8"));
  } catch {}
  // Minimal fallback for the abnormal case where costs.json is missing — still gate the big guns.
  const FALLBACK_BIG = [
    ["prism/leads", 50], ["prism/creator-vet", 50], ["prism/brand-mentions", 50],
    ["prism/share-of-voice", 40], ["korea-gap", 40], ["prism/campaign", 35],
    ["prism/audience-questions", 30], ["prism/reputation", 30], ["employer-brand", 30],
    ["demand-signals", 30], ["prism/org-radar", 26], ["prism/earned-media", 25],
    ["search/everywhere", 20], ["content_analysis/", 20], ["prism/audience-overlap", 20],
    ["prism/crisis-radar", 15],
  ];

  // EVERY number this hook quotes comes out of generated JSON, and one shipped row carries a
  // STRING in a numeric field: `POST web/batch-scrape`.high is "unbounded-by-request" (the
  // vendor publishes no ceiling). That string reached Math.min/Math.max, produced a "~NaN"
  // quote, and — worse — `JSON.stringify({spent: NaN})` is `{"spent":null}`, which the next
  // read takes as 0. One batch-scrape command wiped the whole accumulated session total and
  // re-armed the session cap from zero (checker R1 defect D1). Nothing from costs.json is
  // trusted as a number without passing through `num` (top of main); null means "cannot be
  // computed", which is a fail-safe ask, never a cheap default and never a state write.

  // Normalise a URL before ANY path or param matching. The guard used to decode only %2F
  // (encoded slashes), so `youtube/video/transcr%69pt` slipped past the transcript gate and
  // came out as a plain PAID ask — money-safe (5cr quoted vs 3cr billed) but policy-broken:
  // no per-unit price, no cheaper-route redirect, and the per-unit price is the whole control
  // that replaced the hard block on 08.27.26 (checker R1 defect D6). One decoder, used by
  // every matcher, so the gate and the cost lookup can never disagree about the path.
  //
  // decodeURIComponent throws on a malformed escape (`%zz`, a bare `%`), so the %2F-only
  // decode stays as the fallback. Re-lowercased because a decoded %4A is an uppercase byte
  // that the path character class would truncate on. Where decoding introduces a `&` or a
  // space it can only widen a match — an over-quote or an unreadable-endpoint ask, both safe.
  //
  // It also resolves `.` and `..` path segments, and it has to: curl normalises them
  // CLIENT-SIDE and sends the resolved path, so `credits/../prism/creator-vet` is a 75cr
  // request to /v1/prism/creator-vet — while the guard matched the raw string against the
  // `credits/` -> 0 hardcode and emitted NOTHING at all, and
  // `prism/lookup/../../prism/creator-vet` took the prism/lookup -> 1 hardcode and quoted
  // 1cr informational for the same 75cr call (checker sweep S4). Every prefix test and every
  // costs.json lookup in this file reads a path that came through here, so normalising at
  // this one point closes the bypass for all of them at once. Percent-decoding runs FIRST so
  // an encoded `%2e%2e%2f` cannot hide a dot segment from the resolver.
  function decodeUrl(u) {
    let s = String(u);
    if (/%[0-9a-f]{2}/i.test(s)) { try { s = decodeURIComponent(s); } catch {} }
    return resolveDots(backslashPath(s.replace(/%2f/gi, "/").toLowerCase()));
  }

  // curl treats `\` as a path separator and rewrites it to `/`, so
  // `credits/..\prism/creator-vet` goes on the wire as GET /v1/prism/creator-vet — a 75cr
  // call. resolveDots splits on "/" only, so `..\` was never a dot segment to it, and the
  // path character class then truncated at the backslash and left p="credits/..", which took
  // the `credits/` -> 0 free hardcode: the guard emitted NOTHING AT ALL for calls billing 50,
  // 75, 200 and 10,000 credits, and `credits/..\youtube/video/transcript` slipped the
  // transcript gate entirely — the per-unit-price ask that replaced the hard block on
  // 08.27.26 (checker sweep SW1). Normalising here, before resolveDots, closes it for every
  // prefix test and every costs.json lookup at once.
  //
  // A backslash that is the LAST character of the path is left alone. That shape is the
  // ordinary shell escape of the following `?` (`.../prism/creator-vet\?h=a` in an unquoted
  // URL): the shell removes the backslash and curl never sees it, so rewriting it would turn
  // a correct 75cr quote into a trailing-slash miss. Only a backslash BETWEEN path characters
  // is the separator curl rewrites.
  //
  // DELIBERATE OVER-QUOTE, stated because it is not a mirror of the client: the checker
  // measured that curl only rewrites the backslash when the URL carries NO query string, so
  // `credits/..\prism/share-of-voice?brands=a,b` really is transmitted literally and probably
  // 404s. This normalises it anyway. Pricing it at the resolved endpoint over-quotes a 404,
  // which costs a keystroke; the alternative — reading the truncated `credits/..` — is the
  // silent free pass this defect is made of, and silence on an unknown path is never the safe
  // direction.
  function backslashPath(u) {
    const str = String(u);
    if (!str.includes("\\")) return str;
    const slash = str.indexOf("/");
    if (slash < 0) return str;                 // no path at all; the /v1/ extractor will miss it
    const host = str.slice(0, slash);
    const rest = str.slice(slash);
    const cut = rest.search(/[?#]/);           // query and fragment are handed over verbatim
    const path = cut < 0 ? rest : rest.slice(0, cut);
    const tail = cut < 0 ? "" : rest.slice(cut);
    const trailing = path.endsWith("\\") ? "\\" : "";
    const body = trailing ? path.slice(0, -1) : path;
    return host + body.replace(/\\/g, "/") + trailing + tail;
  }

  // RFC 3986 remove_dot_segments, applied to the path only (the query and fragment are
  // handed to the server verbatim and never take part). Matches what curl 8 puts on the
  // wire, including the "never walk above the root" rule. A path that walks out of /v1/
  // simply stops matching the /v1/ extractor, which lands it on the UNRESOLVED fail-safe
  // ask — unpriceable, never silent, never cheap.
  function resolveDots(u) {
    const str = String(u);
    if (!/(?:^|\/)\.\.?(?:\/|$)/.test(str)) return str;   // fast path: no dot segment present
    const slash = str.indexOf("/");
    if (slash < 0) return str;
    const host = str.slice(0, slash);
    const rest = str.slice(slash);
    const cut = rest.search(/[?#]/);
    const path = cut < 0 ? rest : rest.slice(0, cut);
    const tail = cut < 0 ? "" : rest.slice(cut);
    const out = [];
    for (const seg of path.split("/")) {
      if (seg === ".") continue;
      if (seg === "..") { if (out.length > 1) out.pop(); continue; }  // out[0] is the root ""
      out.push(seg);
    }
    return host + out.join("/") + tail;
  }

  // What a call is quoted at when its endpoint cannot be read from the command at all. Taken
  // from the top of FALLBACK_BIG — the most this hook assumes any single call can cost when
  // the map cannot answer — and stated in the message as a FLOOR, never as a ceiling.
  const UNRESOLVED_FLOOR = FALLBACK_BIG.reduce((a, [, v]) => Math.max(a, v), 5);

  // HTTP verb for this command. curl defaults to GET; an explicit -X/--request wins,
  // otherwise a body flag implies POST. Flags are command-global, so in a chained command
  // a POST flag can be attributed to a sibling GET URL — that OVER-states cost (asks more
  // often) and never under-states it, which is the safe direction for a spend guard.
  // -G/--get (a short-flag bundle like `-sG` too; `-g` is globoff) makes curl send the body
  // flags' data as a GET query string, so the call is a GET (checker X3).
  const VERB = (() => {
    const m = cmd.match(/(?:-X|--request)[=\s]+['"]?([A-Za-z]+)/);
    if (m) return m[1].toUpperCase();
    if (/(?:^|\s)(?:--get|-[A-Za-z]*G[A-Za-z]*)(?=\s|$)/.test(cmd)) return "GET";
    return /(?:^|\s)(?:-d|--data|--data-raw|--data-binary|--data-urlencode|--json)\b/.test(cmd)
      ? "POST"
      : "GET";
  })();

  // Look up a path in the verb-qualified cost map. Falls back through:
  //   exact "VERB path" -> templated match ("web/jobs/{job_id}") -> max across other verbs.
  // Returns null when the map knows nothing about the path.
  // Metered endpoints: the stored number is a UNIT price (per URL / item / chunk / page), so
  // the real spend scales with the array or limit the caller sends. prism/post-stats with 100
  // Instagram URLs is 500 credits, not 1. Quoting the bare number here would be the single
  // most dangerous thing this hook could say.
  // The metered and can't-count entries, built ONCE here from each entry's `metered` and
  // `range` (R10) into the shape every reader below takes: low/high are the label's range, and
  // a null range is a null high — the no-ceiling class, which meteredWorst() turns into the
  // uncomputable ASK. The catalogue names no billing unit and no per-unit rate, so neither is
  // invented (unit/worst stay null); the note is the vendor's own label, verbatim, and `key`
  // names the entry it belongs to, so a message never pins one verb's price on another.
  const PER_UNIT = {};
  for (const k in COSTS || {}) {
    const e = COSTS[k];
    if (k.startsWith("_") || !e || typeof e !== "object" || !(e.metered || e.range === null)) continue;
    PER_UNIT[k] = {
      key: k,
      low: e.range ? e.range[0] : null,
      high: e.range ? e.range[1] : null,
      unit: null,
      worst: null,
      note: e.label,
    };
  }
  const CONDITIONAL = (COSTS && COSTS._conditional) || {};
  const GATED = (COSTS && COSTS._gated) || {};
  const UNPRICED = (COSTS && COSTS._unpriced) || [];

  // Verb-exact first, then path-only. A path match with the wrong verb still warns: over-
  // warning costs a keystroke, under-warning costs credits.
  function tableLookup(table, verb, p) {
    const hit = table[`${verb} ${p}`];
    if (hit) return hit;
    for (const k in table) {
      const sp = k.indexOf(" ");
      if (k.slice(sp + 1) === p) return table[k];
    }
    return null;
  }
  const meteredFor = (verb, p) => tableLookup(PER_UNIT, verb, p);
  const gatedFor = (verb, p) => tableLookup(GATED, verb, p);
  const conditionalFor = (verb, p) => tableLookup(CONDITIONAL, verb, p);

  // A can't-count call with a STATED maximum commits that maximum when it runs (Joe,
  // 09.28.26): prism/investigate its `budget` param ("Holds `budget` credits (default 40, max
  // 200)"), or 200 when none is given; web/sessions 20 ("the 3,600s maximum = 20");
  // economy/imports 20 ("20 credits per call, whatever the limit", 10-06, R18 H1). POST
  // prism/jobs, web/batch-scrape and web/monitors state none, so they commit 0 and ask every
  // time (a stated LIMIT). Verb-exact only: a twin verb on the same path never takes this price.
  // No surcharge overlay is added anywhere: the catalogue labels (09-23, and 10-06 since R18)
  // already include every conditional leg, and the old MANUAL_SURCHARGE table counted all five of its rows twice (Joe, 09.28.26).
  // Two budgets commit the larger; a budget that is not a plain number commits 200, and so does
  // any budget in a command that is not plain (R14a.2: `-K -` or `--expand-data budget=150` can
  // send another budget than the one visible).
  const STATED_MAX = {
    "GET prism/investigate": (url) => {
      const b = plain ? sentValues(url, "budget") : [];
      return b.length && b.every((v) => /^\d+$/.test(v)) ? Math.max(...b.map(Number)) : 200;
    },
    "POST web/sessions": () => 20,
    "GET economy/imports": () => 20,
  };

  // Is URL match `m` an argument of a curl command? Its shell word follows whitespace, and the text
  // back to the nearest command break (a `\`-continued line is not one) starts with `curl` (not
  // `curl =`, a variable). Unsure = no.
  function curlArg(m) {
    let a = m.index;
    while (a > 0 && !/[\s"']/.test(cmd[a - 1])) a--;
    if (a > 0 && /["']/.test(cmd[a - 1])) a--;
    let s = a;
    while (s > 0 && !/[;&|(`{}]/.test(cmd[s - 1]) && !(cmd[s - 1] === "\n" && cmd[s - 2] !== "\\")) s--;
    return a > 0 && /\s/.test(cmd[a - 1]) && /^\s*(?:[^\s'"]*\/)?curl(?:\.exe)?\s+(?![\s=])/i.test(cmd.slice(s, a));
  }

  // The values a query parameter is SENT with, for the one reader that LOWERS a count
  // (investigate's budget; the dry-run reader is gone, R14a.2): it must never honour a parameter
  // the vendor does not receive (checkers X2, X5). `url` is the URL's match in `cmd`, as
  // typed. It must be one whole quoted word that curl receives as typed: the same quote opens and
  // closes it and nothing is glued on after (`"…=1"0` sends `=10`); it is a curl argument, not a literal the shell or a
  // program rewrites (`U="…"; curl "${U%…}"`, `$(echo "…" | sed …)`, a heredoc body, a curl
  // function or alias); it holds no `$`, backtick, backslash or curl glob; and the command has no
  // data or `--url-query` flag, which can send the parameter again (`-G … -d budget=150`). The
  // query stops at `#` (a fragment never leaves curl), splits on `&` as typed, and each name and
  // value is decoded on its own, so an encoded `%26budget=1` stays inside the value it belongs
  // to. Names match exactly as typed. Unsure = no value = full price.
  function sentValues(url, name) {
    let a = url.index;
    while (a > 0 && !/[\s"']/.test(cmd[a - 1])) a--;
    const q = cmd[a - 1];
    const end = url.index + url[0].length;
    if ((q !== '"' && q !== "'") || cmd[end] !== q || !/^[\s;&|)]?$/.test(cmd[end + 1] || "")) return [];
    if (!/^(?:https?:\/\/)?(?:[a-z0-9-]+\.)*$/i.test(cmd.slice(a, url.index)) || /[$`\\{}[\]]/.test(url[0])) return [];
    if (!curlArg(url) || /<<|--url-query|(?:^|\s)(?:--data|--json|-[A-Za-z]*d)|\balias\s+curl\b|\bfunction\s+curl\b|\bcurl\s*\(\s*\)/.test(cmd)) return [];
    const s = url[0].split("#")[0];
    const at = s.indexOf("?");
    const dec = (x) => { try { return decodeURIComponent(x); } catch { return null; } };
    const vals = [];
    for (const kv of at < 0 ? [] : s.slice(at + 1).split("&")) {
      const eq = kv.indexOf("=");
      if (dec(eq < 0 ? kv : kv.slice(0, eq)) === name) vals.push(eq < 0 ? "" : dec(kv.slice(eq + 1)));
    }
    return vals;
  }

  // The figure an entry prices at: the top of its label range (both ends are the same number
  // on a flat label). A null range falls back to the catalogue figure ONLY so the path counts
  // as resolved — never as a price: PER_UNIT above holds every null-range entry, so the call
  // takes the no-ceiling ask before this number is used. Anything not an entry reads as-is.
  const flatOf = (e) =>
    e && typeof e === "object" ? (Array.isArray(e.range) ? e.range[1] : e.credits) : e;

  function lookup(verb, p) {
    if (p.startsWith("_")) return null;
    const exact = flatOf(COSTS[`${verb} ${p}`]);
    if (typeof exact === "number") return exact;
    let other = null;
    const worse = (v) => { other = other === null ? v : Math.max(other, v); };
    for (const k in COSTS) {
      if (k.startsWith("_")) continue;   // _platforms, _conditional, _gated, _unpriced
      const sp = k.indexOf(" ");
      const kv = k.slice(0, sp);
      const kp = k.slice(sp + 1);
      if (!kp.includes("{")) {
        if (kp === p) worse(flatOf(COSTS[k]));
        continue;
      }
      const re = new RegExp(
        "^" + kp.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\\\{[a-z_0-9]+\\\}/gi, "[^/]+") + "$"
      );
      if (!re.test(p)) continue;
      if (kv === verb) return flatOf(COSTS[k]);
      worse(flatOf(COSTS[k]));
    }
    return other;
  }

  // Classify one (already-lowercased) socialcrawl URL.
  // Returns "GATED" | "UNPRICED" | number of credits.
  function costOf(url) {
    const clean = decodeUrl(url); // full percent-decode so gates cannot be hidden by encoding
    const pm = clean.match(/\/v1\/([a-z0-9_/.-]+)/);
    const p = pm ? pm[1].replace(/\?.*$/, "") : "";
    // Gated (was: banned, 08.27.26): any 'transcript' token in the path, or an
    // include=...transcript param. The token test is deliberately broader than the _gated
    // table so a brand-new transcript endpoint is still caught before costs.json knows it.
    if (/transcript/.test(p) || /[?&]include=[^&"'\s]*transcript/.test(clean)) return "GATED";
    // Endpoints the vendor has never published a price for (the cohorts surface). Without
    // this they fall to the 5cr unknown default and the hook states a number that does not
    // exist. Checked before the map: they are absent from it by construction.
    if (UNPRICED.some((pre) => p.startsWith(pre))) return "UNPRICED";
    // credits/* (balance, transactions) are account-meta calls that never touch an upstream
    // platform. They sit outside the published platform catalogue, so they are absent from
    // the generated cost map and would otherwise fall through to the conservative 5cr
    // "unknown endpoint" branch and prompt the user on a free call.
    // The monitors surface (/v1/monitors, /v1/monitors/{id}…: list, get, create, update, delete,
    // runs, timeseries, export) is the same kind (R18-7, Q-h): the spec prices each call at 0
    // (x-credit-cost 0) and keeps it out of the catalogue. A monitor costs its scheduled runs, which
    // the vendor bills at the recipe's price x cadence until it is paused or deleted; no guard sees
    // a run, so the socialcrawl skill states that before one is created. Cohorts stay unpriced.
    if (p.startsWith("credits/") || /^monitors(?:\/|$)/.test(p)) return 0;
    let c;
    if (COSTS) {
      const hit = num(lookup(VERB, p));
      // An endpoint the map cannot resolve is UNPRICEABLE, not cheap. The old 5cr "unknown
      // endpoint" default only looked conservative: four ordinary shell shapes truncate a
      // real URL into junk that still substring-matches the host — a split quote
      // (`.../creator-v""et`), an embedded newline, `"${BASE}"prism/creator-vet`, and
      // `/v1/$EP` — and every one of them landed a 75cr call on the 5cr default, 15x under.
      // Worse, because *a* URL matched, the `urls.length === 0` "assembled from shell
      // variables" fail-safe never fired either (checker R1 defect D3). An unresolvable path
      // now takes its own fail-safe ask with a floor, not a cheap default.
      if (hit === null) return "UNRESOLVED";
      c = hit;                      // authoritative
    } else {
      c = 1;                        // no map (abnormal): default cheap, still gate the big guns
      for (const [k, v] of FALLBACK_BIG) if (p.includes(k)) { c = v; break; }
    }
    // Conditional multipliers (generated): an exact per-endpoint price for the param that
    // flips it. deep_scan is 15 on instagram/comment but only 6 on tiktok/comment, and
    // get_ad_details is 25 on google/company/ads — one blanket floor could not say that.
    let condHit = null;
    for (const r of conditionalFor(VERB, p) || []) {
      if (new RegExp(`[?&]${r.param}=${r.value}(?:[&"'\\s]|$)`, "i").test(clean)) {
        condHit = condHit === null ? r.credits : Math.max(condHit, r.credits);
      }
    }
    if (condHit !== null) {
      c = Math.max(c, condHit);
    } else if (/[?&]deep_scan=true/.test(clean)) {
      // LOAD-BEARING HARDCODE — do not remove. For any endpoint we have NO measured
      // conditional record for, a deep_scan variant bills far higher than its base, so hold
      // the conservative floor of 15. Endpoints that DO have a record use it instead (the
      // branch above), because a real 6 beats a guessed 15. Deleting this floor would let an
      // unknown deep-scan endpoint quote its 1cr base.
      c = Math.max(c, 15);
    }
    return c;
  }

  // PLAIN COMMANDS — the allow-list (R14a.2, Joe 09.28.26: "plain" = the plugin's template
  // grammar plus tidy output). Four patch rounds of repeat readers each left new silent
  // under-count shapes (checkers X1, X4, X5-X7, X8-X11); a deny-list of shapes cannot close that
  // class, an allow-list can. The guard stays silent only for a command it fully reads:
  //   - backslash-newline continuations joined, then split on top-level `&&`, `;` and newlines
  //     (outside quotes) into segments, each a full-line `#` comment, `sleep <digits>`, or a
  //     plain curl call;
  //   - a plain curl call: the first word is exactly `curl` (no prefix, no path, not curl.exe),
  //     then only -s -S -sS -N -f/--fail, --max-time <digits>, -X GET|POST|PUT|PATCH|DELETE,
  //     -H <quoted header>, -d '<single-quoted literal>' (no @), -o <literal path>,
  //     -w '<single-quoted format>' and exactly one URL word. Every other flag is not plain;
  //   - the URL word is one whole quoted string naming socialcrawl.dev or a subdomain over
  //     https://…/v1/, with no $, backtick, backslash, whitespace, { } [ ] or #, and a path
  //     (before `?`) with no % and no `.` or `..` segment;
  //   - a header holds only $NAME, ${NAME} or exactly $(cat <one literal path>), no backtick;
  //   - the optional tail: `| jq …`, `| head …`, `| python -m json.tool` / `| python3 -m
  //     json.tool` stages whose arguments hold no $ or backtick, then `> path`, `>> path`,
  //     `2>/dev/null` or `2>&1`.
  // A heredoc, `<<<`, $'…', `||`, `&`, `( )`, any other pipe, a trailing comment or an
  // unbalanced quote is not plain, and every socialcrawl.dev occurrence in the command must sit
  // in the URL word of a plain curl segment (a URL in a header, a body or a comment is not).
  // Unsure = not plain = the ask: the money-safe direction.
  const LIT_PATH = /^[A-Za-z0-9_.\/~+,:@=-]+$/;
  function plainCommand(src) {
    // 1. Tokens: words (with their quoting) and operators; `\`-newline outside single quotes joins.
    const toks = [];
    const OP = /(?:(\d+)?(>>|>&|>\||>|<<<|<<-?|<&|<>|<)|&>>?|&&|\|\||\|&|\||;;&?|;&|;|&|\(|\)|\n)/y;
    let i = 0;
    let lineStart = true;
    while (i < src.length) {
      const c = src[i];
      if (c === "\\" && src[i + 1] === "\n") { i += 2; continue; }
      if (c === " " || c === "\t") { i++; continue; }
      if (c === "#") {                                   // a comment runs to the end of its line
        while (i < src.length && src[i] !== "\n") i++;
        toks.push({ comment: true, lineStart });
        lineStart = false;
        continue;
      }
      OP.lastIndex = i;
      const m = OP.exec(src);
      if (m) {
        toks.push({ op: m[2] || m[0], fd: m[1] || "" });
        lineStart = m[0] === "\n";
        i += m[0].length;
        continue;
      }
      const parts = [];                                  // [{t: "u"|"s"|"d", v}]
      const add = (t, v) => {
        const last = parts[parts.length - 1];
        if (t === "u" && last && last.t === "u") last.v += v; else parts.push({ t, v });
      };
      let raw = "";
      while (i < src.length && !" \t\n|&;()<>".includes(src[i])) {
        const ch = src[i];
        if (ch === "\\") {
          if (src[i + 1] === "\n") { i += 2; continue; }
          add("u", src.slice(i, i + 2)); raw += src.slice(i, i + 2); i += 2; continue;
        }
        if (ch === "'") {
          const e = src.indexOf("'", i + 1);
          if (e < 0) return false;                       // unbalanced
          add("s", src.slice(i + 1, e)); raw += src.slice(i, e + 1); i = e + 1; continue;
        }
        if (ch === '"') {
          let e = i + 1;
          while (e < src.length && src[e] !== '"') e += src[e] === "\\" ? 2 : 1;
          if (e >= src.length) return false;             // unbalanced
          add("d", src.slice(i + 1, e)); raw += src.slice(i, e + 1); i = e + 1; continue;
        }
        if (ch === "`" || (ch === "$" && (src[i + 1] === "'" || src[i + 1] === '"'))) return false;
        add("u", ch); raw += ch; i++;
      }
      const one = parts.length === 1 ? parts[0] : null;
      toks.push({ raw, lit: one && one.t === "u" ? one.v : undefined, q: one && one.t !== "u" ? one : null });
      lineStart = false;
    }
    // 2. The pieces of a plain curl.
    const litPath = (t) => (t.lit !== undefined && LIT_PATH.test(t.lit)) || (!!t.q && t.q.v !== "" && !/[$`\\\n]/.test(t.q.v));
    function headerOk(v) {
      if (/[`\n]/.test(v)) return false;
      const re = /\$(?:[A-Za-z_][A-Za-z0-9_]*|\{[A-Za-z_][A-Za-z0-9_]*\}|\(cat [A-Za-z0-9_.\/~+,:@=-]+\))/y;
      for (let j = v.indexOf("$"); j >= 0; j = v.indexOf("$", j)) {
        re.lastIndex = j;
        const hit = re.exec(v);
        if (!hit) return false;
        j += hit[0].length;
      }
      return true;
    }
    function urlOk(v) {
      const m = /^https:\/\/(?:[a-z0-9-]+\.)*socialcrawl\.dev(\/v1\/[^?]*)(?:\?.*)?$/i.exec(v);
      if (!m || /[\s$`\\{}[\]#"']/.test(v) || m[1].includes("%")) return false;
      return !m[1].split("/").some((s) => s === "." || s === "..");
    }
    const FLAGS = new Set(["-s", "-S", "-sS", "-N", "-f", "--fail"]);
    const METHODS = new Set(["GET", "POST", "PUT", "PATCH", "DELETE"]);
    const isWord = (t) => !!t && !t.op && !t.comment;
    // The number of socialcrawl.dev occurrences in a plain curl segment's URL word; -1 = not plain.
    function curlSeg(seg) {
      if (seg[0].lit !== "curl") return -1;
      let k = 1;
      let url = null;
      for (; k < seg.length && isWord(seg[k]); k++) {
        const t = seg[k];
        const nw = isWord(seg[k + 1]) ? seg[k + 1] : null;
        if (FLAGS.has(t.lit)) continue;
        if (nw && ((t.lit === "--max-time" && /^\d+$/.test(nw.lit || "")) ||
            (t.lit === "-X" && METHODS.has(nw.lit)) ||
            (t.lit === "-H" && nw.q && headerOk(nw.q.v)) ||
            (t.lit === "-d" && nw.q && nw.q.t === "s" && !nw.q.v.includes("@")) ||
            (t.lit === "-o" && litPath(nw)) ||
            (t.lit === "-w" && nw.q && nw.q.t === "s"))) { k++; continue; }
        if (!url && t.q && urlOk(t.q.v)) { url = t.q.v; continue; }
        return -1;
      }
      if (!url) return -1;
      while (k < seg.length && seg[k].op === "|" && !seg[k].fd) {       // tidy output stages
        const stage = [];
        for (k++; k < seg.length && isWord(seg[k]); k++) stage.push(seg[k]);
        const [a, ...rest] = stage;
        if (!a) return -1;
        if (a.lit === "python" || a.lit === "python3") {
          if (!(rest.length === 2 && rest[0].lit === "-m" && rest[1].lit === "json.tool")) return -1;
        } else if ((a.lit !== "jq" && a.lit !== "head") || rest.some((t) => /[$`]/.test(t.raw))) return -1;
      }
      for (; k < seg.length; k += 2) {                                  // then the redirects
        const r = seg[k];
        const t = seg[k + 1];
        if (!isWord(t)) return -1;
        if (!((!r.fd && (r.op === ">" || r.op === ">>") && litPath(t)) ||
            (r.fd === "2" && r.op === ">" && t.lit === "/dev/null") ||
            (r.fd === "2" && r.op === ">&" && t.lit === "1"))) return -1;
      }
      return (url.match(/socialcrawl\.dev/gi) || []).length;
    }
    // 3. Segments: split on top-level `&&`, `;` and newlines.
    const segs = [[]];
    for (const t of toks) {
      if (t.op === "&&" || t.op === ";" || t.op === "\n") segs.push([]);
      else segs[segs.length - 1].push(t);
    }
    let inUrls = 0;
    for (const seg of segs) {
      if (!seg.length) continue;
      if (seg[0].comment) { if (seg.length === 1 && seg[0].lineStart) continue; return false; }
      if (seg.length === 2 && seg[0].lit === "sleep" && /^\d+$/.test(seg[1].lit || "")) continue;
      const n = curlSeg(seg);
      if (n < 0) return false;
      inUrls += n;
    }
    // Every socialcrawl.dev in the command must be inside a plain curl's URL word.
    return inUrls > 0 && inUrls === (src.match(/socialcrawl\.dev/gi) || []).length;
  }
  let plain = false;
  try { plain = plainCommand(cmd); } catch {}           // local wrap (F-F8): unsure = not plain

  // EVERY socialcrawl API URL in the command (chained curls, &&, ;, pipes). `found` keeps each
  // match as typed, with its offset, for sentValues(). In a plain command each is a curl's URL
  // word; in any other command these are only the URLs visible in it (the not-plain ask).
  const found = [...cmd.matchAll(/socialcrawl\.dev\/v1\/[^"'\s]*/gi)];
  const urls = found.map((m) => m[0].toLowerCase());

  // ---------------------------------------------------------------------------
  // COMMAND-LEVEL costing. One Bash command can chain several SocialCrawl calls,
  // so the decision, the figure quoted, and the session charge are all per
  // COMMAND — never per first-URL. Quoting only the first hit under-quoted a
  // 280cr chain as "1-5 credits" and, worse, produced a self-contradiction: a
  // later deep_scan leg said "pins this call at 15" while the closing line still
  // said "quote the 5 ceiling". Fixed 08.27.26 (checker R1 defect U1).
  // ---------------------------------------------------------------------------

  function pathOf(u) {
    const clean = decodeUrl(u);
    const pm = clean.match(/\/v1\/([a-z0-9_/.-]+)/);
    return pm ? pm[1].replace(/\?.*$/, "") : "";
  }

  // Worst case for ONE metered row: its PUBLISHED CEILING, always. Null only when
  // costs.json cannot produce a number for it at all.
  // Shared by the metered path and the transcript gate — the gate needs it because the
  // `transcript` token also catches the BATCH rows, which are metered entries, not _gated.
  //
  // THERE IS NO QUANTITY DISCOUNT HERE, DELIBERATELY. Two attempts have been made and both
  // under-quoted:
  //   1. A generic param family (limit|count|max_results|per_page|page_size) applied to any
  //      metered row. On GET prism/comments the vendor is explicit that `max` "drives
  //      billing" while `limit` "truncates only the returned set, never what was scanned or
  //      billed", so `?limit=1` quoted 5 against a 200 ceiling — 40x under (defect D5).
  //   2. The row's own `driver` field read as a query-param name. But `driver` is free-text
  //      UNIT prose ("comment page", "50-id chunk", "response-determined"), and the checker's
  //      audit of all 31 _perUnit rows against the in-tree vendor openapi
  //      (research/socialcrawl-docs-2026-08-27/openapi.json) found 6 rows with a bare-word
  //      driver — probe, leg, url, url, page, ttl_seconds — and ZERO of the 6 naming a real
  //      billing query param: probe/leg/url/page do not exist on those endpoints at all, and
  //      ttl_seconds is body-only with the wrong units (seconds vs browser-hour). So the
  //      discount could only ever fire on a param that does not bill. It quoted 1 credit for
  //      `POST web/crawl?page=1&limit=10000`, a 10,000cr call — 10,000x under (sweep S2).
  //
  // Direction is the whole argument: the ceiling is the fallback, so ANY multiplier here can
  // only quote LESS. A discount is safe only on a param provably identified as the billing
  // driver by the vendor spec, and no shipped row supplies one. Over-quoting costs a
  // confirmation keystroke; under-quoting costs credits. When in doubt, ceiling.
  function meteredWorst(m) {
    return num(m.high);                    // null = no published ceiling (defect D1)
  }

  // Worst case for ONE call, and what kind of call it is.
  //   kind: "gated" | "unpriced" | "metered" | "flat"
  //   worst: credits this single call can cost at its ceiling
  function classify(u, i) {
    const p = pathOf(u);
    // costOf already applies the conditional pin and the deep_scan floor to the flat price.
    const base = costOf(u);
    const m = meteredFor(VERB, p);

    if (base === "GATED") {
      const g = gatedFor(VERB, p);
      // A transcript price is PER UNIT. 10 is the non-YouTube rate and the conservative
      // pick when the generated table has no row (a brand-new transcript endpoint).
      const band = g ? num(g.credits) : null;
      // The `transcript` substring also catches the BATCH rows — `youtube/transcripts`
      // (plural) is a metered entry, not in _gated — and costOf short-circuited to "GATED"
      // before the metered lookup ever ran. A call whose published ceiling is 300 credits
      // was quoted at the generic 10cr band, 30x under, and the counter recorded 10
      // (checker R1 defect D2). The gate still fires — the ask, the per-unit price and the
      // cheaper route ARE the policy — but the number inside it has to be the billable one.
      const mw = m ? meteredWorst(m) : null;
      return {
        p,
        kind: "gated",
        worst: Math.max(band === null ? 10 : band, mw === null ? 0 : mw),
        unit: g ? g.unit : (m && m.unit) || "item",
        g,
        m,
        mw,
      };
    }
    if (base === "UNRESOLVED") {
      // The path could not be resolved against the cost map, so no price for it exists here.
      // Quoted at the FALLBACK_BIG floor and described as a floor — the big prism endpoints
      // this shape can hide bill 50-200.
      return { p, kind: "unresolved", worst: UNRESOLVED_FLOOR };
    }
    if (base === "UNPRICED") {
      // Contributes 0 to the command total ON PURPOSE: the vendor publishes no figure and
      // this hook must not invent one. The message says that in words instead.
      return { p, kind: "unpriced", worst: 0 };
    }

    // No dry-run discount (R14a.2, Joe 09.28.26, supersedes P8): a `dry_run=1` is counted at
    // its full price, because a hidden ~/.curlrc, `-K`, `--expand-data` or `--request-target`
    // can change what curl sends. costs.json's `dryRun` field stays a vendor fact nothing here reads.
    const flat = num(base) === null ? 0 : base;
    if (m) {
      const w = meteredWorst(m);
      if (w === null) {
        // A PRICED row whose ceiling is not a number — its label is a sentence, so no worst
        // case exists to quote. It contributes only its STATED maximum, if the vendor states
        // one (STATED_MAX, verb-exact), and 0 otherwise, like an unpriced row, because any other
        // figure would be invented; the dedicated ask branch states the vendor's own price,
        // verbatim, and that no worst case can be computed from it.
        const stated = m.key === `${VERB} ${p}` && STATED_MAX[m.key] ? STATED_MAX[m.key](found[i]) : 0;
        return { p, kind: "uncomputable", worst: stated, m };
      }
      // Never below what the flat price or a conditional pin already established.
      return { p, kind: "metered", worst: Math.max(w, flat), m };
    }
    return { p, kind: "flat", worst: flat };
  }

  const calls = urls.map(classify);
  const nCalls = calls.length;
  const gatedCalls = calls.filter((c) => c.kind === "gated");
  const unpricedCalls = calls.filter((c) => c.kind === "unpriced");
  const meteredCalls = calls.filter((c) => c.kind === "metered");
  const uncomputableCalls = calls.filter((c) => c.kind === "uncomputable");
  const unresolvedCalls = calls.filter((c) => c.kind === "unresolved");
  // Worst case for the whole COMMAND: every call's ceiling, added up. Sanitised on the way
  // in: a single un-quotable leg must not turn the command figure into NaN (defect D1).
  const cmdWorst = calls.reduce((a, c) => a + (num(c.worst) === null ? 0 : c.worst), 0);
  // The log's paths (R14b, O5): each visible call's path as the cost lookup read it ([a-z0-9_/.-],
  // no query string). Every `sc_` run anywhere in it, up to the next /, ? or #, is logged as `sc_…`
  // (J5): never a key, even one typed into the middle of a path. The rest of the path is kept.
  const logPaths = () => calls.map((c) => `/v1/${c.p.replace(/sc_[^/?#]*/gi, "sc_…")}`);

  // Free, and nothing to warn about -> silent pass, and no session write. Only for a plain
  // command: a free visible URL in any other command still asks (R14a.2: `--request-target` or
  // `--variable --expand-url` can send a paid call behind a free credits/* URL).
  if (
    plain &&
    cmdWorst === 0 &&
    !gatedCalls.length &&
    !unpricedCalls.length &&
    !meteredCalls.length &&
    !uncomputableCalls.length &&
    !unresolvedCalls.length
  ) return done();

  // The session so far. What is counted is the QUOTED WORST CASE of every paid command that
  // ran — an upper bound, because the vendor refunds a held ceiling down to the work actually
  // done — so the total runs HIGH by design; the ledger reconciles the real spend. It reaches
  // every paid path: until 08.27.26 the expensive calls never incremented it, and three 75cr
  // creator-vets followed by a 1cr call read back as "session ~1cr" (checker R1 defect U2).
  // A state file written by an older build (`{"spent":N}`) still reads. Read under the lock (X7).
  await lock();
  st = readState();
  // A lost total (J4) is saved as lost at once, deny paths included, so the rest of the session
  // keeps the cap off and makes no balance read; if that save fails too, or this run has no lock,
  // the next call reads the file again and, finding it damaged, ends the same way.
  if (st.lost) writeState(st);
  // The balance read (R14b): once per session, on a command whose visible worst case is above 0
  // (so never on a free command or one with no /v1/ URL in it), never for an unattended command
  // that is not plain, which is denied whatever the balance is (J1), and never once the session's
  // committed total is lost (J4). A read balance is cached whatever its value, so 0-3 or a
  // negative gives no cap and is not read again; a failed try caches nothing and is counted, and
  // after 3 the session stops trying. The state is written here, so a deny below keeps the cache
  // and the count. The try is counted and saved BEFORE it is made: a state that can't be saved
  // can't hold a balance or a count, so it is never read (checker X1), and the call itself is
  // then refused by recorded(), or denied unattended.
  if (!st.lost && cmdWorst > 0 && (plain || !UNATTENDED) && num(st.balance) === null && (num(st.balanceFails) || 0) < 3) {
    const fails = num(st.balanceFails) || 0;
    st.balanceFails = fails + 1;
    if (writeState(st)) {
      const b = await readBalance();
      if (b !== null) {
        st.balance = b;
        st.balanceFails = fails;
        writeState(st);
      }
    }
  }
  const spent = st.spent;
  // The cap (Design 2; R18-1, Joe 10.06.26): valid only on an integer balance >= 4, as min(500, 25% of it); anything
  // else — no balance cached, a string, 0-3, a negative, or a lost total (J4) — is null, and a
  // null cap makes every paid command a crossing (an unreadable balance counts as one).
  const balance = st.balance;
  const cap = !st.lost && Number.isInteger(balance) && balance >= 4 ? Math.min(500, Math.floor(0.25 * balance)) : null;
  // Why there is no cap (A20): a lost total (J4) is not an unread balance, and its ~0 is no total.
  const noCap = st.lost
    ? `This session's committed total was lost (its session file is damaged or unreadable), so there is no cap to stay under for the rest of this session.`
    : `I couldn't read your balance, so there is no cap to stay under.`;
  const committed = st.lost ? "" : `~${spent} credits are committed this session. `;
  const spendLine = st.lost ? ` This session's committed total was lost.` : ` Session spend ~${spent}cr so far.`;

  // Conditional params actually present in this command, ALL of them. The caller needs to be
  // told that the param THEY set is what pins a call to the top of its range.
  const condHits = urls
    .map((u) => {
      const clean = decodeUrl(u);
      const p = pathOf(u);
      const on = (conditionalFor(VERB, p) || []).filter((r) =>
        new RegExp(`[?&]${r.param}=${r.value}(?:[&"'\\s]|$)`, "i").test(clean));
      return on.length ? { p, on } : null;
    })
    .filter(Boolean);
  const condLine = condHits
    .map(
      (h) =>
        ` You set ` +
        h.on.map((r) => `\`${r.param}=${r.value}\``).join(" and ") +
        ` on /v1/${h.p}, which pins this call at ` +
        `${Math.max(...h.on.map((r) => r.credits))} credits — that is the exact ` +
        `figure, not an estimate.`
    )
    .join("");

  // Roster of every SocialCrawl endpoint in the command with its own ceiling, then the
  // command total. Only for chains (and the not-plain ask, which names every visible URL): a
  // single call's figure is already stated in full by its own branch, and repeating it is noise.
  const tagOf = (c) =>
    c.kind === "gated"
      ? ` (per ${c.unit}, so it multiplies by how many you request)`
      : c.kind === "unpriced"
      ? ` (unpriced — no vendor figure exists, so it is NOT in the total)`
      : c.kind === "uncomputable"
      ? ` (NO computable ceiling: the vendor prices ${(c.m && c.m.key) || "it"} by a sentence, ` +
        (c.worst ? `not a figure, so it is counted at its stated maximum)` : `not a figure, so it is NOT in the total)`)
      : c.kind === "unresolved"
      ? ` (endpoint unreadable — that figure is a FLOOR, not a ceiling)`
      : "";
  // An unresolved call may have no readable path at all, so it is named, not printed as "/v1/".
  const labelOf = (c) => (c.p ? `/v1/${c.p}` : "an unreadable /v1/ URL");
  // An uncomputable leg with no stated maximum is listed WITHOUT a figure: it contributes
  // nothing to the total, and "up to ~0cr" beside a call with no ceiling would read as a quote.
  const roster = calls
    .map((c) => (c.kind === "uncomputable" && !c.worst ? `${labelOf(c)}${tagOf(c)}` : `${labelOf(c)} up to ~${c.worst}cr${tagOf(c)}`))
    .join("; ");
  const caveat =
    (gatedCalls.length
      ? ` That total is a FLOOR, not a ceiling — the transcript leg bills per ` +
        `${gatedCalls[0].unit}, so it multiplies by the number of items.`
      : "") +
    (unpricedCalls.length
      ? ` It also excludes an unpriced call the vendor publishes no figure for.`
      : "") +
    (uncomputableCalls.some((c) => !c.worst)
      ? ` It also excludes a call no ceiling can be computed for — the vendor prices it by a ` +
        `sentence, not a figure.`
      : "") +
    (unresolvedCalls.length
      ? ` One leg's endpoint could not be read from the command, so its ${UNRESOLVED_FLOOR}cr ` +
        `share of that total is a floor, not a ceiling.`
      : "");

  const chainLine = nCalls > 1
    ? ` This command makes ${nCalls} SocialCrawl calls — ${roster}. Worst case for the whole ` +
      `command: ~${cmdWorst} credits.${caveat}`
    : "";

  // Presence detection for the local transcription route. PRESENCE ONLY — an env var and a
  // filename on PATH. Nothing is executed and nothing is read; this cannot tell whether the
  // pipeline actually works, so the message it feeds must be worded as an observation ("I see
  // a key here"), never as a promise. Runs only inside the transcript branch, never on the
  // hot path.
  function localRouteDetected() {
    try {
      if (process.env.GROQ_API_KEY) return "a GROQ_API_KEY in this environment";
      const win = process.platform === "win32";
      const exts = win ? ["", ".exe", ".cmd", ".bat"] : [""];
      const dirs = String(process.env.PATH || "").split(win ? ";" : ":").slice(0, 64);
      for (const d of dirs) {
        if (!d) continue;
        for (const b of ["whisper", "whisper-cli", "whisper.cpp", "faster-whisper", "whisperx"]) {
          for (const e of exts) {
            try { if (existsSync(join(d, b + e))) return `\`${b}\` on your PATH`; } catch {}
          }
        }
      }
    } catch {}
    return null;
  }

  // The transcript sentence: the per-unit price, the cheaper catalog route, and — only when
  // detected — the local route. Both the gate below and the not-plain ask carry it whenever a
  // transcript URL is visible, so no command shape strips the number out of the message.
  const gc = gatedCalls.find((c) => c.g) || gatedCalls[0];
  function transcriptLine() {
    const g = gc.g;

    const local = localRouteDetected();
    const localLine = local
      ? ` I see ${local} — so there is also a local route: pull the media URL (about 1 credit, ` +
        `or free if you already have it) and transcribe it there for $0 in credits. That is a ` +
        `detected key/binary, not a guarantee the pipeline is configured and working.`
      : "";

    const body = g
      ? `/v1/${gc.p} bills ${g.credits} credits PER ` +
        `${g.unit} — 100 of them = ${num(g.credits) * 100} credits. Cheaper first: ${g.cheaper}.`
      : gc.m && gc.mw !== null && /transcript/.test(gc.p)
      ? // A BATCH transcript row: a metered entry, absent from _gated. Quote ITS numbers — its
        // ceiling, and the per-unit price in the vendor's own label — not the generic band:
        // this row's ceiling is 30x the band (defect D2). Gated on the PATH carrying the
        // transcript token: an `&include=transcript` bolted onto some other metered endpoint
        // is not a batch transcript row and takes the generic band below.
        `/v1/${gc.p} is a BATCH transcript endpoint: ONE call carries a published ceiling of ` +
        `${gc.m.high} credits — not the ~10cr a single transcript costs. The vendor's own price ` +
        `for it: "${gc.m.note}". Cheaper first: ` +
        (gc.p.startsWith("youtube/")
          ? `GET youtube/video/subtitles — 1 credit per video, the same words straight off the ` +
            `caption track.`
          : `pull the media URL from that platform's post/media endpoint (usually 1-5 credits) ` +
            `and transcribe it yourself.`)
      : // No _gated row: a transcript token the generated table does not know (a new endpoint,
        // or `&include=transcript` bolted onto another paid call). Still quote the real band.
        `SocialCrawl's transcript endpoints bill 3 credits per video on YouTube and 10 credits ` +
        `per item on every other platform, charged per item and not per request. Cheaper first: ` +
        `GET youtube/video/subtitles is 1 credit for the same words on YouTube; elsewhere, pull ` +
        `the media URL from that platform's post/media endpoint (usually 1-5 credits) and ` +
        `transcribe it yourself. If this is an \`include=transcript\` parameter, it adds a paid ` +
        `transcript leg to a call that is already billing.`;
    return `SocialCrawl TRANSCRIPT call — this is paid compute, not a caption download. ${body}${localLine}`;
  }

  // DECISION — one decision for the whole command, at the worst severity present:
  // not plain > gated > unreadable > unbounded > unpriced > cap step > silent. Every ask goes
  // through decide(): attended it parks this command's worst case as pending; unattended it denies.

  // 0. Not a plain command (R14a.2) -> the one NOT A PLAIN CURL ask, whatever else it carries. It
  //    names the total of the SocialCrawl URLs visible in it (the figure parked as pending and
  //    committed once it runs), the transcript sentence when a transcript URL is visible, and the
  //    cap step when that total crosses one. It replaces the loop and shell-variable asks: both
  //    shapes are not plain.
  if (!plain) {
    const crossing = cmdWorst > 0 && (cap === null || Math.floor((spent + cmdWorst) / cap) > Math.floor(spent / cap));
    return decide(
      `SocialCrawl command NOT A PLAIN CURL: it carries a SocialCrawl URL but is not plain \`curl\` ` +
        `calls this guard fully reads (a loop, a pipe into a program, a wrapper, a variable, a ` +
        `heredoc, a note or other mention, or a flag outside the plain set), so what it sends, and ` +
        `how many times, can't be read from it. ` +
        (nCalls
          ? `Visible counted total: ~${cmdWorst} credits (${roster}).${caveat}`
          : `Visible counted total: ~0 credits (no SocialCrawl /v1/ URL can be read in it).`) +
        ` That counts only what is visible; the command may send more.` +
        (gatedCalls.length ? ` It includes a ${transcriptLine()}` : "") +
        (crossing
          ? ` Session cap step: ${committed}` +
            (cap === null
              ? noCap
              : `The cap is ${cap} credits (the smaller of 500 and a quarter of your ${balance}-credit ` +
                `balance), and this command's visible total crosses its next step.`)
          : ""),
      cmdWorst,
      "not-plain",
      ` Confirm with the user what this command does and what it will cost before running it; ` +
        (cmdWorst > 0
          ? `once it runs, the visible total is counted.`
          : `its visible total is 0, so nothing is counted for it.`) +
        ` A single call rewritten as a plain curl is counted without this ask.`
    );
  }

  // 1. Transcript endpoints anywhere in the command -> ASK with the price and the redirect.
  //    Changed from `deny` 08.27.26 (findings §08.27.26b). The three things this message must
  //    always carry are the per-unit price, the cheaper catalog route, and — only when
  //    detected — the local route. Runs on an explicit yes only.
  if (gatedCalls.length) {
    // The billable worst case for THIS command, always stated. For a batch row that is the
    // multiplied ceiling, not the per-item band — the gate used to name no figure at all for
    // a single call, which is how a 300cr endpoint rode out on a 10cr band (defect D2).
    // chainLine already carries the figure (and the FLOOR caveat) when there is more than one call.
    const gatedTotal =
      nCalls > 1
        ? ""
        : ` Worst case for this call: ~${cmdWorst} credits` +
          (gc.mw !== null && gc.mw >= cmdWorst
            ? ` — the row's published ceiling for ONE call.`
            : ` — and that is a FLOOR, not a ceiling: it bills per ${gc.unit}, so it ` +
              `multiplies by how many you request.`);

    return decide(
      transcriptLine() +
        chainLine +
        gatedTotal,
      cmdWorst,
      "transcript",
      ` Show the user that price and the cheaper route, and run this only on an explicit yes.`
    );
  }

  // 1a-. Endpoint unreadable -> fail-safe ask: a plain curl whose literal URL names a path the
  //     cost map cannot resolve. (A truncated or assembled URL is not plain; it asks above.)
  if (unresolvedCalls.length) {
    return decide(
      `SocialCrawl call with an UNREADABLE endpoint: the URL in this command is truncated or ` +
        `assembled at runtime — split quoting, an embedded line break, \`${"${BASE}"}\`, \`$EP\` — so ` +
        `the path cannot be resolved against the cost map and its price is unknown. Treat it as ` +
        `AT LEAST ~${UNRESOLVED_FLOOR} credits: that is a floor, not a ceiling, and the prism ` +
        `endpoints this shape can hide bill 50-200.` +
        condLine + chainLine + spendLine,
      cmdWorst,
      "unreadable",
      ` Re-run it with the full literal URL, or confirm the endpoint and its cost with the user ` +
        `before sending.`
    );
  }

  // 1a. No ceiling can be computed -> ask, and say plainly that no worst case exists. This is
  //     the branch that used to quote "~NaN" and write {"spent":null} (defect D1). What keeps
  //     it safe is the same thing that keeps the transcript gate safe: the price is always in
  //     the message — here the vendor's own label, verbatim, for the entry it belongs to. The
  //     catalogue prices these by a sentence, not a figure, and names no unit or rate, so the
  //     message states none of its own (R10) — except a stated maximum (STATED_MAX), which is
  //     what the call commits once it runs.
  if (uncomputableCalls.length) {
    const uc = uncomputableCalls[0];
    const h = uc.m || {};
    // The path-only fallback can match another verb's entry (GET web/monitors -> POST
    // web/monitors). The ask stays — over-warning costs a keystroke — but it says whose price
    // it is quoting, and never pins that verb's price on this one.
    const twin = h.key && h.key.slice(0, h.key.indexOf(" ")) !== VERB;
    return decide(
      `SocialCrawl call with NO computable ceiling: /v1/${uc.p}. The vendor prices ` +
        `${h.key || "it"} by a sentence, not a figure: "${h.note}".` +
        (twin
          ? ` This command reads as a ${VERB}; that price is for ${h.key} on the same path, ` +
            `which this hook cannot rule out.`
          : "") +
        (uc.worst
          ? ` This hook cannot compute a worst case from a sentence; it counts this call at its ` +
            `stated maximum, ~${uc.worst} credits, once it runs.`
          : ` This hook cannot compute a worst case from a sentence, so this call is NOT in the ` +
            `command total or the session counter below.`) +
        condLine + chainLine + spendLine,
      cmdWorst,
      "uncomputable",
      ` Work out what it will cost from that price, state it to the user, and get explicit ` +
        `approval before sending.`
    );
  }

  // 1b. Unpriced endpoint -> ask, and say plainly that the price is unknown.
  if (unpricedCalls.length) {
    return decide(
      "SocialCrawl UNPRICED endpoint: the vendor publishes no credit cost for this call, so " +
        "nothing here can quote it — do not guess a number. The cohorts surface also handles " +
        "audience/PII data." + chainLine,
      cmdWorst,
      "unpriced",
      " Confirm with the user what this is for before running it, and read the actual charge " +
        "back from credits_used afterwards."
    );
  }

  // 2. A cap step (Design 5): this command takes the session's committed total across the next
  //    multiple of the cap, or the cap is unknown. One ask, naming the committed total, the cap,
  //    this command's worst case and the balance. Metered and flat calls ask only here: the
  //    per-call ladder (every metered call, every flat >= 5, every 15cr) is retired (Joe).
  if (cap === null || Math.floor((spent + cmdWorst) / cap) > Math.floor(spent / cap)) {
    return decide(
      `SocialCrawl session cap step: this command's worst case is ~${cmdWorst} credits` +
        (st.lost ? `. ` : `, and ${committed}`) +
        (cap === null
          ? noCap
          : `The cap is ${cap} credits (the smaller of 500 and a quarter of your ${balance}-credit ` +
            `balance), and this command crosses its next step.`) +
        condLine + chainLine,
      cmdWorst,
      "cap-step",
      (cap === null
        ? st.lost ? ` Every paid call asks for the rest of this session.` : ` Every paid call asks until the balance is read.`
        : "") +
        ` Show the user those figures and run it only on a yes; once it runs it is counted.`
    );
  }
  // 3. Under the cap: nothing is emitted (Design 3), and this command's worst case is committed
  //    now — the CLI's own permission prompt can still decline it, an over-count, the safe
  //    direction. A pending quote left by an earlier declined ask of this same command is
  //    dropped, so the Post run cannot count it a second time. Unattended, the pass is logged.
  //    A commit that can't be recorded (TEMP missing or read-only, a full disk, a folder at the
  //    state path, no session lock) would leave this call uncounted, so recorded() refuses it.
  st.spent = spent + cmdWorst;
  delete st.pending[hash];
  if (!recorded()) return;
  if (UNATTENDED) logUnattended(sid, "pass", "under-cap", logPaths(), cmdWorst, st.spent, cap);
  return done();
} catch {
  return failed(sid); // an unexpected error -> pass attended, deny unattended (R14b)
} finally {
  await unlock();
}
}

main().catch(() => failed(null));
