"""
dump_cookies.py ... auto-extract cookies from the running browser-use session.

What this does (plain English):
  It finds the Chromium instance that the browser-use MCP server is currently
  running, attaches to its remote-debug port, asks it for all cookies, and
  writes them out as a Netscape-format cookies.txt file. That file is the
  same format httpx, curl, and yt-dlp all understand.

  Works on macOS, Linux, and Windows. Process discovery branches by OS:
    - macOS / Linux: `ps aux`
    - Windows: PowerShell `Get-CimInstance Win32_Process`

What it expects:
  - The browser-use MCP server is currently running (i.e. you have an active
    Claude Code session with the browser-use MCP loaded). If the browser was
    closed, this script can't find anything to dump.

How to run:
  ~/.iss/venv/bin/python ${CLAUDE_SKILL_DIR}/../scripts/dump_cookies.py output/<course>/metadata/cookies.txt
  ~/.iss/venv/bin/python ${CLAUDE_SKILL_DIR}/../scripts/dump_cookies.py output/<course>/metadata/cookies.txt --domain eastwesthealing.com

Why this exists:
  Manual cookie export means installing a Chrome extension, logging in twice
  (once in browser-use, once in your normal Chrome), and remembering to
  re-export when cookies expire. This script removes all of that. Log in
  once via browser-use, then any time you want to bulk-pull pages, run this
  to refresh the cookie file. Fully automated.
"""

import argparse
import asyncio
import json
import platform
import re
import subprocess
import sys
from pathlib import Path

import httpx
import websockets


# Windows consoles default to cp1252; force UTF-8 so non-ASCII never crashes
# a print(). No-op where already UTF-8 or not reconfigurable.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass


def find_cdp_port() -> int:
    """Scan running processes for the browser-use Chromium's remote-debug port.
    Works on macOS, Linux, and Windows."""
    system = platform.system()

    if system == "Windows":
        # Use PowerShell + CIM. wmic is deprecated in Win11; Get-CimInstance is the
        # forward-compatible path. Filter to processes whose CommandLine contains the
        # remote-debugging-port flag so we get the actual Chromium fork, not its parent.
        ps_cmd = (
            "Get-CimInstance Win32_Process | "
            "Where-Object { $_.CommandLine -match 'remote-debugging-port=' } | "
            "Select-Object -ExpandProperty CommandLine"
        )
        result = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps_cmd],
            capture_output=True, text=True,
        )
        haystack = result.stdout
    else:
        # macOS and Linux: ps aux dumps every process with its full command line.
        result = subprocess.run(["ps", "aux"], capture_output=True, text=True)
        haystack = result.stdout

    matches = re.findall(r"remote-debugging-port=(\d+)", haystack)
    if not matches:
        raise RuntimeError(
            "No debuggable Chromium found (no process with a "
            "remote-debugging-port). The chosen browser backend isn't exposing "
            "a CDP port. Fall back to the manual cookie-paste path in /login."
        )
    # Multiple matches usually mean the same port repeated across forks; just take the first.
    return int(matches[0])


async def dump_cookies(port: int, domain_filter: str | None) -> list[dict]:
    """Connect to CDP and pull all cookies via the Storage.getCookies command."""
    # Step 1: discover the WebSocket URL from the CDP HTTP /json/version endpoint.
    info = httpx.get(f"http://127.0.0.1:{port}/json/version", timeout=5.0).json()
    ws_url = info["webSocketDebuggerUrl"]

    # Step 2: connect and request all cookies at the browser level.
    async with websockets.connect(ws_url, max_size=64 * 1024 * 1024) as ws:
        await ws.send(json.dumps({"id": 1, "method": "Storage.getCookies"}))
        while True:
            msg = json.loads(await ws.recv())
            if msg.get("id") == 1:
                break
        cookies = msg.get("result", {}).get("cookies", [])

    if domain_filter:
        df = domain_filter.lower().lstrip(".")
        cookies = [c for c in cookies if df in c.get("domain", "").lower()]
    return cookies


def to_netscape(cookies: list[dict]) -> str:
    """Convert CDP cookie dicts into Netscape-format cookies.txt text."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by dump_cookies.py from the running browser-use session.",
        "# https://curl.se/docs/http-cookies.html",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # CDP gives expires as a float seconds since epoch; session cookies have -1 or 0.
        expires = c.get("expires", 0)
        expires_int = int(expires) if expires and expires > 0 else 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, include_subdomains, path, secure, str(expires_int), name, value]))
    return "\n".join(lines) + "\n"


async def main_async(args: argparse.Namespace) -> int:
    port = find_cdp_port()
    print(f"Found browser-use Chromium on CDP port {port}")
    cookies = await dump_cookies(port, args.domain)
    if not cookies:
        print("No cookies found. Are you logged in?", file=sys.stderr)
        return 1
    out_path = Path(args.output).expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(to_netscape(cookies), encoding="utf-8")
    print(f"Wrote {len(cookies)} cookies to {out_path}")
    if args.domain:
        print(f"  (filtered to domain containing '{args.domain}')")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Dump cookies from the running browser-use Chromium.")
    parser.add_argument("output", help="Path to write the Netscape cookies.txt file")
    parser.add_argument("--domain", default=None,
                        help="Only export cookies whose domain contains this string (e.g. eastwesthealing.com)")
    args = parser.parse_args()
    return asyncio.run(main_async(args))


if __name__ == "__main__":
    sys.exit(main())
